// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
  namespace App {
    // interface Error {}
    interface Locals {
      correlationId: string;
    }
    // interface PageData {}
    // interface PageState {}
    // interface Platform {}
  }
}

// Environment variable types are auto-generated by SvelteKit in
// $env/static/private and $env/static/public. See .env.example for
// the variables this app expects:
//
//   API_BASE_URL      — Backend API base URL (server-side only)
//   PUBLIC_APP_NAME   — App display name (available on client)

export {};
